# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 11:00
from __future__ import unicode_literals

import Lima.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=10)),
                ('person_id', models.CharField(default=Lima.models.agent_id, editable=False, max_length=5, primary_key=True, serialize=False)),
                ('password', models.CharField(default=Lima.models.random_string, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('town_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lima.Person')),
            ],
            bases=('Lima.person', models.Model),
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lima.Person')),
                ('agentId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lima.Agent')),
            ],
            bases=('Lima.person',),
        ),
        migrations.AddField(
            model_name='markets',
            name='town_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Lima.Town'),
        ),
        migrations.AddField(
            model_name='agent',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lima.Markets'),
        ),
    ]
