# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:18
from __future__ import unicode_literals

import Lima.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CropToFarmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crop', models.CharField(max_length=40)),
                ('farmer', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(default=Lima.models.random_string, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lima.District')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lima.Person')),
            ],
            bases=('Lima.person', models.Model),
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Lima.Person')),
                ('market_agent', models.CharField(max_length=10, verbose_name=Lima.models.Agent)),
                ('town', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lima.Town')),
            ],
            bases=('Lima.person',),
        ),
        migrations.AddField(
            model_name='market',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lima.Town'),
        ),
        migrations.AddField(
            model_name='agent',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lima.Market'),
        ),
    ]
