# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='verified',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
