# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='agentId',
            field=models.CharField(max_length=10),
        ),
    ]
