# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lima', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Markets',
            new_name='Market',
        ),
    ]
