# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lima', '0002_auto_20161006_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
