# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lima', '0002_auto_20161011_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name_plural': 'Verification'},
        ),
    ]
