# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lima', '0003_auto_20161010_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='district',
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='market',
            name='district',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Lima.District'),
        ),
    ]
