# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lima', '0004_auto_20161011_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={},
        ),
    ]
